sudo: false

language: node_js
node_js:
  - 10

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn --non-interactive --frozen-lockfile

branches:
  only:
    - master
